version: '3.8'

services:
    nginx:
        image: nginx:alpine
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=loyaltykad
            - DB_USERNAME=root
            - DB_PASSWORD=password
        ports:
            - 9000

    mysql:
        image: mysql:latest
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=loyaltykad
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - '3306:3306'

    vite:
        image: node:24.2-alpine
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - '5173:5173'
        command: npm run dev
        depends_on:
            - app

volumes:
    mysql_data:
